@url = http://localhost:8080/flashcard
### FLASHCARD ###
### findById flashcard

GET {{url}}/1 HTTP/1.1

### add a flashcard

POST {{url}}/add HTTP/1.1
Content-Type: application/json

    {
        "flashcardSet": {
            "flashcardSetId": 2
        },
        "frontData": "White",
        "backData": "Blanco"
    }

### update a flashcard

PUT {{url}}/update/9 HTTP/1.1
Content-Type: application/json

    {
        "flashcardId": 9,
        "flashcardSet": {
            "flashcardSetId": 2
        },
        "frontData": "Pink",
        "backData": "Rosa"
    }

### delete a flashcard

DELETE {{url}}/delete/10 HTTP/1.1
Content-Type: application/json

### FLASHCARD SET ###
### findByFlashcardSetId flashcard set

GET {{url}}/set/1 HTTP/1.1

### findAll flashcard sets

GET {{url}}/set/all HTTP/1.1